### PR TITLE
Added support for validating epoch timestamps

### PR DESCRIPTION
**Pull request by 00willo**

### CODE REVIEW

**Comment by 00willo** [comment]
Not sure what I'm missing as to why the tests I added are failing in travis-ci, across all 3.4, 3.5 and 3.6 python versions.

I'm using 3.4 locally, and all tests are passing, either running test manually or invoking tox.

**Comment by shopnilsazal** [comment]
Hi Williamson,

First of all, this package is to validate string only. So add `@validate_str` decorator before your function. If you need integer you can convert it inside the function. Then write test with passing argument as string like `isepoch('-62135633092')`. I am giving you the failing log, so that you can find out the reason.
```
Traceback (most recent call last):
  File "/home/travis/build/shopnilsazal/validus/tests/test_validators.py", line 394, in test_isepoch
    self.assertTrue(validus.isepoch(-62135633092))
AssertionError: False is not true
```

Thanks.

**Comment by 00willo** [comment]
Ah OK, I wasn't aware that the purpose was to validate strings only.  That should be updated in the docs somewhere to make it clearer.  So, from that I take it, this is all about input validation then?

I'll make the changes.

**Comment by 00willo** [comment]
Still failing but only in travis.  As shown below, `test_isepoch` is clearly passing when I run it in my local dev environment.  I deleted my virtualenv and recreated it from scratch just to make sure I didn't do something silly

```
[willo@dev-vm validus (master)]$ mkvirtualenv -p python3 validus
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/willo/.virtualenvs/validus/bin/python3
Not overwriting existing python script /home/willo/.virtualenvs/validus/bin/python (you must use /home/willo/.virtualenvs/validus/bin/python3)
Installing setuptools, pip, wheel...done.
(validus) [willo@dev-vm validus (master)]$ pip install tox
Requirement already satisfied: tox in /home/willo/.virtualenvs/validus/lib/python3.4/site-packages
Requirement already satisfied: pluggy<1.0,>=0.3.0 in /home/willo/.virtualenvs/validus/lib/python3.4/site-packages (from tox)
Requirement already satisfied: py>=1.4.17 in /home/willo/.virtualenvs/validus/lib/python3.4/site-packages (from tox)
Requirement already satisfied: virtualenv>=1.11.2; python_version != "3.2" in /home/willo/.virtualenvs/validus/lib/python3.4/site-packages (from tox)
(validus) [willo@dev-vm validus (master)]$ git checkout add_is_epoch        
Switched to branch 'add_is_epoch'
(validus) [willo@dev-vm validus (add_is_epoch)]$ python --version
Python 3.4.5
(validus) [willo@dev-vm validus (add_is_epoch)]$ export TOXENV=py34
(validus) [willo@dev-vm validus (add_is_epoch)]$ tox -e ${TOXENV}
GLOB sdist-make: /home/willo/git/validus/setup.py
py34 inst-nodeps: /home/willo/git/validus/.tox/dist/validus-0.1.0.zip
py34 installed: validus==0.1.0
py34 runtests: PYTHONHASHSEED='1567651218'
py34 runtests: commands[0] | python setup.py test
running test
running egg_info
writing top-level names to validus.egg-info/top_level.txt
writing validus.egg-info/PKG-INFO
writing dependency_links to validus.egg-info/dependency_links.txt
reading manifest file 'validus.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no files found matching '*.rst' under directory 'docs'
warning: no files found matching 'conf.py' under directory 'docs'
warning: no files found matching 'Makefile' under directory 'docs'
warning: no files found matching 'make.bat' under directory 'docs'
warning: no files found matching '*.jpg' under directory 'docs'
writing manifest file 'validus.egg-info/SOURCES.txt'
running build_ext
test_isisbn (tests.test_isbn.TestIsbn) ... ok
test_isisbn10 (tests.test_isbn.TestIsbn) ... ok
test_isisbn13 (tests.test_isbn.TestIsbn) ... ok
test_isphone (tests.test_phones.TestPhones) ... ok
test_isascii (tests.test_validators.TestValidators) ... ok
test_isbase64 (tests.test_validators.TestValidators) ... ok
test_isbytelen (tests.test_validators.TestValidators) ... ok
test_iscrcard (tests.test_validators.TestValidators) ... ok
test_isdatauri (tests.test_validators.TestValidators) ... ok
test_isdns (tests.test_validators.TestValidators) ... ok
test_isemail (tests.test_validators.TestValidators) ... ok
test_isepoch (tests.test_validators.TestValidators) ... ok
test_isfilepath (tests.test_validators.TestValidators) ... ok
test_isfloat (tests.test_validators.TestValidators) ... ok
test_isfullwidth (tests.test_validators.TestValidators) ... ok
test_ishalfwidth (tests.test_validators.TestValidators) ... ok
test_ishexcolor (tests.test_validators.TestValidators) ... ok
test_ishexdecimal (tests.test_validators.TestValidators) ... ok
test_isiban (tests.test_validators.TestValidators) ... ok
test_isint (tests.test_validators.TestValidators) ... ok
test_isip (tests.test_validators.TestValidators) ... ok
test_isipv4 (tests.test_validators.TestValidators) ... ok
test_isipv6 (tests.test_validators.TestValidators) ... ok
test_isisin (tests.test_validators.TestValidators) ... ok
test_isiso8601 (tests.test_validators.TestValidators) ... ok
test_isjson (tests.test_validators.TestValidators) ... ok
test_islatitude (tests.test_validators.TestValidators) ... ok
test_islongitude (tests.test_validators.TestValidators) ... ok
test_ismac (tests.test_validators.TestValidators) ... ok
test_ismd5 (tests.test_validators.TestValidators) ... ok
test_ismongoid (tests.test_validators.TestValidators) ... ok
test_ismultibyte (tests.test_validators.TestValidators) ... ok
test_isport (tests.test_validators.TestValidators) ... ok
test_isprintascii (tests.test_validators.TestValidators) ... ok
test_isrgbcolor (tests.test_validators.TestValidators) ... ok
test_issemver (tests.test_validators.TestValidators) ... ok
test_isslug (tests.test_validators.TestValidators) ... ok
test_isssn (tests.test_validators.TestValidators) ... ok
test_istime (tests.test_validators.TestValidators) ... ok
test_isurl (tests.test_validators.TestValidators) ... ok
test_isuuid (tests.test_validators.TestValidators) ... ok
test_isuuid3 (tests.test_validators.TestValidators) ... ok
test_isuuid4 (tests.test_validators.TestValidators) ... ok
test_isuuid5 (tests.test_validators.TestValidators) ... ok

----------------------------------------------------------------------
Ran 44 tests in 0.124s

OK
_______________________________________________________________________________________________________________________ summary _______________________________________________________________________________________________________________________
  py34: commands succeeded
  congratulations :)
```

**Comment by shopnilsazal** [comment]
Hi Williamson,
It's failing in `Python 3.5.3`. Can you please install `Python 3.5.3` with pyenv and check again? 

Thanks.

**Pull request closed without merging**
